version: "3.8"

services:

  web_dashboard:
    build:
      context: "."
      dockerfile: "Dockerfile"
      args:
        VITE_API_BASE: ""
        VITE_MEDIA_BASE: ""
    image: web-dashboard:latest
    container_name: web_dashboard
    ports:
      - "0.0.0.0:8010:8010"
    restart: unless-stopped
    networks:
      - botnet

networks:
  botnet:
    driver: bridge